<a href="https://colab.research.google.com/github/IshaqKassam/AI-ML-Group-Task/blob/main/AI_ML_GROUP_TASK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [235]:
import pandas as pd 
import numpy as np

In [236]:
from numpy import array
from sklearn.preprocessing import Normalizer
from keras.activations import sigmoid
from keras.losses import mse
from numpy.random import uniform

Hyperparameters

In [237]:
batch_size=2

Dataset

In [238]:
data={'Day 1':[30,40,50,20,15,60],'Day 2':[40,50,20,15,60,70],
      'Day 3':[50,20,15,60,70,50],'Target':[20,15,60,70,50,40]}

In [239]:
dataset=pd.DataFrame(data)

In [240]:
dataset

Day 1  Day 2  Day 3  Target
0     30     40     50      20
1     40     50     20      15
2     50     20     15      60
3     20     15     60      70
4     15     60     70      50
5     60     70     50      40

In [241]:
X=dataset.drop('Target',axis=1)
y=dataset['Target']

In [242]:
X

Day 1  Day 2  Day 3
0     30     40     50
1     40     50     20
2     50     20     15
3     20     15     60
4     15     60     70
5     60     70     50

In [243]:
X_norm = Normalizer(norm='max').fit_transform(X)

In [244]:
X_norm

array([[0.6       , 0.8       , 1.        ],
       [0.8       , 1.        , 0.4       ],
       [1.        , 0.4       , 0.3       ],
       [0.33333333, 0.25      , 1.        ],
       [0.21428571, 0.85714286, 1.        ],
       [0.85714286, 1.        , 0.71428571]])

In [245]:
array(y)

array([20, 15, 60, 70, 50, 40])

In [246]:
np.reshape(array(y),(1,-1))

array([[20, 15, 60, 70, 50, 40]])

In [247]:
y_norm=Normalizer(norm='max').fit_transform(np.reshape(array(y),(1,-1)))

In [248]:
y_norm

array([[0.28571429, 0.21428571, 0.85714286, 1.        , 0.71428571,
        0.57142857]])

ANN From Scratch

In [249]:
"""weight_1=array([[.2,.1],[.3,.1],[.2,.1]])
weight_2=array([[.5],[.1]])"""

'weight_1=array([[.2,.1],[.3,.1],[.2,.1]])\nweight_2=array([[.5],[.1]])'

Define shape for the weights

In [250]:
weight_1=uniform(-1,1,(3,2)) #shape 3 by 2
weight_2=uniform(-1,1,(2,1))

In [251]:
weight_1

array([[ 0.83330572, -0.04332881],
       [-0.53623118,  0.76290298],
       [-0.06589349, -0.76977947]])

In [252]:
X_norm[0:batch_size]

array([[0.6, 0.8, 1. ],
       [0.8, 1. , 0.4]])

In [253]:
output_1=X_norm[0:batch_size]@weight_1
output_1

array([[ 0.00510499, -0.18545437],
       [ 0.104056  ,  0.42032815]])

In [254]:
act_output=sigmoid(output_1).numpy()
act_output

array([[0.50127625, 0.45376884],
       [0.52599055, 0.60356177]])

In [255]:
pred_output=act_output@weight_2
pred_output=np.reshape(pred_output,(1,-1))

Mean Squared Error

In [256]:
y_true=y_norm[0][0:batch_size]
y_pred=pred_output
y_pred

array([[-0.08073483,  0.03017961]])

In [257]:
y_true

array([0.28571429, 0.21428571])

In [258]:
y_hat = (mse(y_true,y_pred).numpy())[0]

In [259]:
y_hat

0.08409000693300848

Expected Output = y

In [260]:
y = 0.909

Backward Propagation

We have the 'y - expected output' , 'y_hat - predicted output', we want f'(h)

f'(h) = y_hat(1-y_hat)

In [261]:
fod_sigmoid = y_hat * (1-y_hat)
fod_sigmoid

0.07701887766701507

Error(k) = (y-y_hat)[fod_sigmoid]

In [262]:
diff=y-y_hat
diff

0.8249099930669915

In [266]:
error_k=diff * fod_sigmoid
error_k

0.06353364184232486