<a href="https://colab.research.google.com/github/IshaqKassam/AI-ML-Group-Task/blob/main/AI_ML_GROUP_TASK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [319]:
import pandas as pd 
import numpy as np

In [320]:
from numpy import array
from sklearn.preprocessing import Normalizer
from keras.activations import sigmoid
from keras.losses import mse
from numpy.random import uniform

Hyperparameters

In [321]:
batch_size=1

Dataset

In [322]:
data={'Day 1':[30,40,50,20,15,60],'Day 2':[40,50,20,15,60,70],
      'Day 3':[50,20,15,60,70,50],'Target':[20,15,60,70,50,40]}

In [323]:
dataset=pd.DataFrame(data)

In [324]:
dataset

Day 1  Day 2  Day 3  Target
0     30     40     50      20
1     40     50     20      15
2     50     20     15      60
3     20     15     60      70
4     15     60     70      50
5     60     70     50      40

In [325]:
X=dataset.drop('Target',axis=1)
y=dataset['Target']

In [326]:
X

Day 1  Day 2  Day 3
0     30     40     50
1     40     50     20
2     50     20     15
3     20     15     60
4     15     60     70
5     60     70     50

In [327]:
X_norm = Normalizer(norm='max').fit_transform(X)

In [328]:
X_norm

array([[0.6       , 0.8       , 1.        ],
       [0.8       , 1.        , 0.4       ],
       [1.        , 0.4       , 0.3       ],
       [0.33333333, 0.25      , 1.        ],
       [0.21428571, 0.85714286, 1.        ],
       [0.85714286, 1.        , 0.71428571]])

In [329]:
array(y)

array([20, 15, 60, 70, 50, 40])

In [330]:
np.reshape(array(y),(1,-1))

array([[20, 15, 60, 70, 50, 40]])

In [331]:
y_norm=Normalizer(norm='max').fit_transform(np.reshape(array(y),(1,-1)))

In [332]:
y_norm

array([[0.28571429, 0.21428571, 0.85714286, 1.        , 0.71428571,
        0.57142857]])

ANN From Scratch

In [333]:
"""weight_1=array([[.2,.1],[.3,.1],[.2,.1]])
weight_2=array([[.5],[.1]])"""

'weight_1=array([[.2,.1],[.3,.1],[.2,.1]])\nweight_2=array([[.5],[.1]])'

Define shape for the weights

In [334]:
weight_1=uniform(-1,1,(3,2)) #shape 3 by 2
weight_2=uniform(-1,1,(2,1))

these are the weights for the outer layer where col 1 is the j weights and col 2 are the i weights

In [335]:
weight_1

array([[ 0.06813004, -0.77534544],
       [-0.30763227,  0.53622603],
       [ 0.5549366 ,  0.55182841]])

these are the weights for the hidden layer where the row 1 is jk and row 2 is the ik

In [336]:
weight_2

array([[ 0.98925472],
       [-0.59047364]])

Having the number of epochs as 100

In [337]:
for i in range(100):
  X_norm[0:batch_size]
  output_1=X_norm[0:batch_size]@weight_1
  act_output=sigmoid(output_1).numpy()
  pred_output=act_output@weight_2
  pred_output=np.reshape(pred_output,(1,-1))

In [338]:
act_output

array([[0.58654697, 0.62611879]])

In [339]:
y_hat = pred_output
y_hat

array([[0.21053771]])

In [340]:
y_norm

array([[0.28571429, 0.21428571, 0.85714286, 1.        , 0.71428571,
        0.57142857]])

Backward Propagation

We have the 'y_norm - expected output' , 'y_hat - predicted output', we want f'(h)

f'(h) = y_hat(1-y_hat) //we'll need an matrix of 1's for the multiplication


In [341]:
ones_matrix = uniform(1,1,(1,1))
ones_matrix

array([[1.]])

Error(k) = (y-y_hat)*y_hat(1-y_hat)

In [342]:
error_k = (y_norm - y_hat) * (y_hat*(ones_matrix - y_hat))
error_k

array([[0.01249522, 0.00062296, 0.10747327, 0.13121778, 0.08372875,
        0.05998424]])

In [343]:
error_k

array([[0.01249522, 0.00062296, 0.10747327, 0.13121778, 0.08372875,
        0.05998424]])

In [344]:
error_k_const = error_k[0][0]
error_k_const

0.012495217405070447

output for node i and j

In [345]:
nj_out = act_output[:,0]
nj_out

array([0.58654697])

In [346]:
ni_out = act_output[:,1] #the 2nd col
ni_out

array([0.62611879])

weights jk and ik - hidden layer

In [347]:
weight_2_j = uniform(weight_2[0], weight_2[0], (1,1))
weight_2_j

array([[0.98925472]])

In [348]:
weight_2_i = uniform(weight_2[1], weight_2[1], (1,1))
weight_2_i

array([[-0.59047364]])

Error at the inner layer - hidden layer for node j and i

In [349]:
error_j = error_k_const * weight_2_j * nj_out * (1 - nj_out)
error_j

array([[0.00299765]])

In [350]:
error_i = error_k_const * weight_2_i * ni_out * (1 - ni_out)
error_i

array([[-0.00172717]])

Delta Rule

𝑊𝑛𝑒𝑤 = 𝑊𝑐𝑢𝑟𝑟𝑒𝑛𝑡 + Δ𝑊𝑐𝑢𝑟𝑟𝑒𝑛t
Δ𝑊𝑐𝑢𝑟𝑟𝑒𝑛𝑡 𝑖𝑠 𝑐𝑜𝑚𝑝𝑢𝑡𝑒𝑑 𝑎𝑠 (𝜂) [ 𝐸𝑟𝑟𝑜𝑟(𝑘) ] (𝑂𝑘)

In [351]:
learning_rate = 0.03 #from the slides

In [352]:
hidden_layer_errors = np.concatenate((error_j, error_i), axis=1)
hidden_layer_errors

array([[ 0.00299765, -0.00172717]])

In [353]:
hidden_layer_outputs = np.concatenate((nj_out, ni_out), axis=0)

In [354]:
hidden_layer_outputs

array([0.58654697, 0.62611879])

In [355]:
hidden_layer_outputs = np.reshape(hidden_layer_outputs, (1,2))
hidden_layer_outputs

array([[0.58654697, 0.62611879]])

Finding delta for weight_1

In [356]:
delta_weight_1 = learning_rate * hidden_layer_errors * hidden_layer_outputs
delta_weight_1

array([[ 5.27478751e-05, -3.24423794e-05]])

Adjusting weight_1

In [357]:
new_weight_1 = weight_1 + delta_weight_1
new_weight_1

array([[ 0.06818278, -0.77537788],
       [-0.30757952,  0.53619359],
       [ 0.55498935,  0.55179597]])

Finding delta for weight_2

In [358]:
error_output_layer = np.reshape(array(error_k_const), (1,1))
error_output_layer

array([[0.01249522]])

In [359]:
delta_weight_2 = learning_rate * error_output_layer * pred_output
delta_weight_2

array([[7.89214344e-05]])

Adjusting weight 2

In [360]:
new_weight_2 = weight_2 + delta_weight_2
new_weight_2

array([[ 0.98933364],
       [-0.59039472]])

In [361]:
i

99

In [362]:
weight_1 = new_weight_1
weight_2 = new_weight_2

In [363]:
weight_1

array([[ 0.06818278, -0.77537788],
       [-0.30757952,  0.53619359],
       [ 0.55498935,  0.55179597]])

In [364]:
weight_2

array([[ 0.98933364],
       [-0.59039472]])