<a href="https://colab.research.google.com/github/IshaqKassam/AI-ML-Group-Task/blob/main/AI_ML_GROUP_TASK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import pandas as pd 
import numpy as np

In [26]:
from numpy import array
from sklearn.preprocessing import Normalizer
from keras.activations import sigmoid
from keras.losses import mse
from numpy.random import uniform

Hyperparameters

In [27]:
batch_size=2

Dataset

In [28]:
data={'Day 1':[30,40,50,20,15,60],'Day 2':[40,50,20,15,60,70],
      'Day 3':[50,20,15,60,70,50],'Target':[20,15,60,70,50,40]}

In [29]:
dataset=pd.DataFrame(data)

In [30]:
dataset

Day 1  Day 2  Day 3  Target
0     30     40     50      20
1     40     50     20      15
2     50     20     15      60
3     20     15     60      70
4     15     60     70      50
5     60     70     50      40

In [31]:
X=dataset.drop('Target',axis=1)
y=dataset['Target']

In [32]:
X

Day 1  Day 2  Day 3
0     30     40     50
1     40     50     20
2     50     20     15
3     20     15     60
4     15     60     70
5     60     70     50

In [33]:
X_norm = Normalizer(norm='max').fit_transform(X)

In [34]:
X_norm

array([[0.6       , 0.8       , 1.        ],
       [0.8       , 1.        , 0.4       ],
       [1.        , 0.4       , 0.3       ],
       [0.33333333, 0.25      , 1.        ],
       [0.21428571, 0.85714286, 1.        ],
       [0.85714286, 1.        , 0.71428571]])

In [35]:
array(y)

array([20, 15, 60, 70, 50, 40])

In [36]:
np.reshape(array(y),(1,-1))

array([[20, 15, 60, 70, 50, 40]])

In [37]:
y_norm=Normalizer(norm='max').fit_transform(np.reshape(array(y),(1,-1)))

In [38]:
y_norm

array([[0.28571429, 0.21428571, 0.85714286, 1.        , 0.71428571,
        0.57142857]])

ANN From Scratch

In [39]:
"""weight_1=array([[.2,.1],[.3,.1],[.2,.1]])
weight_2=array([[.5],[.1]])"""

'weight_1=array([[.2,.1],[.3,.1],[.2,.1]])\nweight_2=array([[.5],[.1]])'

In [40]:
weight_1=uniform(-1,1,(3,2)) #shape 3 by 2
weight_2=uniform(-1,1,(2,1))

In [41]:
weight_1

array([[-0.3416523 , -0.24169441],
       [ 0.53251267,  0.28532377],
       [-0.75311224, -0.99259406]])

In [42]:
X_norm[0:batch_size]

array([[0.6, 0.8, 1. ],
       [0.8, 1. , 0.4]])

In [43]:
output_1=X_norm[0:batch_size]@weight_1
output_1

array([[-0.53209348, -0.90935169],
       [-0.04205406, -0.30506938]])

In [44]:
act_output=sigmoid(output_1).numpy()
act_output

array([[0.37002875, 0.28713252],
       [0.48948803, 0.4243187 ]])

In [45]:
pred_output=act_output@weight_2
pred_output=np.reshape(pred_output,(1,-1))

Mean Squared Error

In [46]:
y_true=y_norm[0][0:batch_size]
y_pred=pred_output

In [47]:
y_true

array([0.28571429, 0.21428571])

In [48]:
mse(y_true,y_pred).numpy()

array([0.49111294])